server:
  port: 8080

spring:
  application:
    name: employee

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/postgres_demo
    password: ${POSTGRES_PASSWORD}
    username: ${POSTGRES_USER}


spring.jpa:
  hibernate:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect